# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages
RUN npm install -g nodemon ts-node && npm install

# Bundle app source
COPY . .

# The container will listen on this port
EXPOSE 3000

# Command to run the application in development
CMD [ "npm", "run", "dev" ]
